name: Build docker dev images

on:
  push:
    branches: master


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.ACCESS_TOKEN_REPO }}
    
    steps:
    - uses: actions/checkout@v2

    - name: build x64
      run: |
        VERSION=$(curl -sX GET "https://api.github.com/repos/Forceu/barcodebuddy/releases/latest" | awk '/tag_name/{print $4; exit}' FS='[""]')
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-x64.yml/dispatches \
        -d '{"ref": "master", "inputs": {"version": "${VERSION}"}}'
    - name: build arm32
      run: |
        VERSION=$(curl -sX GET "https://api.github.com/repos/Forceu/barcodebuddy/releases/latest" | awk '/tag_name/{print $4; exit}' FS='[""]')
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-arm32.yml/dispatches \
        -d '{"ref": "master", "inputs": {"version": "${VERSION}"}}'
    - name: build arm64
      run: |
        VERSION=$(curl -sX GET "https://api.github.com/repos/Forceu/barcodebuddy/releases/latest" | awk '/tag_name/{print $4; exit}' FS='[""]')
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-arm64.yml/dispatches \
        -d '{"ref": "master", "inputs": {"version": "${VERSION}"}}'
