name: Build docker release images

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.ACCESS_TOKEN_REPO }}
    
    steps:
    - uses: oprypin/find-latest-tag@v1
      with:
        repository: Forceu/barcodebuddy 
        releases-only: true 
        prefix: 'v'
      id: latestversion

    - uses: actions/checkout@v2

    - name: build multiarch
      run: |
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-release.yml/dispatches \
        -d '{"ref": "master", "inputs": {"version": "${{ steps.latestversion.outputs.tag }}"}}'
