on:
  push:
    branches: master


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.ACCESS_TOKEN_REPO }}
    
    steps:
    - uses: actions/checkout@v2

    - name: build x64
      run: |
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-x64.yml/dispatches \
        -d '{"ref": "master", 
             "inputs": {
                "name": "Push to master"}
        }'
    - name: build arm32
      run: |
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-arm32.yml/dispatches \
        -d '{"ref": "master", 
             "inputs": {
                "name": "Push to master"}
        }'
    - name: build arm64
      run: |
        curl -u ":$TOKEN" \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/forceu/barcodebuddy-docker/actions/workflows/docker-publish-arm64.yml/dispatches \
        -d '{"ref": "master", 
             "inputs": {
                "name": "Push to master"}
        }'
